export const CURRENT_WEEK = 8
export const ALL_MATCHES = [
  // --- WEEK 8 ---
  {
    id: "w8m1",
    teamA: "BTR",
    teamB: "GEEK",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w8m2",
    teamA: "DEWA",
    teamB: "ONIC",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w8m3",
    teamA: "EVOS",
    teamB: "NAVI",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w8m4",
    teamA: "TLID",
    teamB: "RRQ",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w8m5",
    teamA: "ONIC",
    teamB: "AE",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w8m6",
    teamA: "DEWA",
    teamB: "EVOS",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w8m7",
    teamA: "AE",
    teamB: "BTR",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w8m8",
    teamA: "RRQ",
    teamB: "NAVI",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  // --- WEEK 9 ---
  {
    id: "w9m1",
    teamA: "BTR",
    teamB: "DEWA",
    scoreA: 0,
    scoreB: 0,
    isPlayed: false,
  },
  {
    id: "w9m2",
    teamA: "TLID",
    teamB: "AE",
    scoreA: 0,
    scoreB: 0,
    isPlayed: false,
  },
  {
    id: "w9m3",
    teamA: "GEEK",
    teamB: "TLID",
    scoreA: 0,
    scoreB: 0,
    isPlayed: false,
  },
  {
    id: "w9m4",
    teamA: "AE",
    teamB: "RRQ",
    scoreA: 0,
    scoreB: 0,
    isPlayed: false,
  },
  {
    id: "w9m5",
    teamA: "BTR",
    teamB: "ONIC",
    scoreA: 0,
    scoreB: 0,
    isPlayed: false,
  },
  {
    id: "w9m6",
    teamA: "RRQ",
    teamB: "DEWA",
    scoreA: 0,
    scoreB: 0,
    isPlayed: false,
  },
  {
    id: "w9m7",
    teamA: "ONIC",
    teamB: "EVOS",
    scoreA: 0,
    scoreB: 0,
    isPlayed: false,
  },
  {
    id: "w9m8",
    teamA: "NAVI",
    teamB: "GEEK",
    scoreA: 0,
    scoreB: 0,
    isPlayed: false,
  },
  // --- COMPLETED ---
  // --- WEEK 1 ---
  {
    id: "w1m1",
    teamA: "BTR",
    teamB: "AE",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w1m2",
    teamA: "NAVI",
    teamB: "RRQ",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w1m3",
    teamA: "EVOS",
    teamB: "GEEK",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w1m4",
    teamA: "AE",
    teamB: "ONIC",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w1m5",
    teamA: "TLID",
    teamB: "NAVI",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w1m6",
    teamA: "DEWA",
    teamB: "BTR",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w1m7",
    teamA: "EVOS",
    teamB: "TLID",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w1m8",
    teamA: "RRQ",
    teamB: "ONIC",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  // --- WEEK 2 ---
  {
    id: "w2m1",
    teamA: "ONIC",
    teamB: "GEEK",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w2m2",
    teamA: "DEWA",
    teamB: "NAVI",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w2m3",
    teamA: "GEEK",
    teamB: "BTR",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w2m4",
    teamA: "AE",
    teamB: "EVOS",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w2m5",
    teamA: "TLID",
    teamB: "DEWA",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w2m6",
    teamA: "NAVI",
    teamB: "AE",
    scoreA: 1,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w2m7",
    teamA: "RRQ",
    teamB: "TLID",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w2m8",
    teamA: "BTR",
    teamB: "EVOS",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  // --- WEEK 3 ---
  {
    id: "w3m1",
    teamA: "ONIC",
    teamB: "DEWA",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w3m2",
    teamA: "NAVI",
    teamB: "EVOS",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w3m3",
    teamA: "TLID",
    teamB: "GEEK",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w3m4",
    teamA: "ONIC",
    teamB: "BTR",
    scoreA: 1,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w3m5",
    teamA: "RRQ",
    teamB: "AE",
    scoreA: 1,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w3m6",
    teamA: "BTR",
    teamB: "NAVI",
    scoreA: 1,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w3m7",
    teamA: "GEEK",
    teamB: "RRQ",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w3m8",
    teamA: "AE",
    teamB: "DEWA",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  // --- WEEK 4 ---
  {
    id: "w4m1",
    teamA: "NAVI",
    teamB: "ONIC",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w4m2",
    teamA: "EVOS",
    teamB: "DEWA",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w4m3",
    teamA: "TLID",
    teamB: "BTR",
    scoreA: 1,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w4m4",
    teamA: "RRQ",
    teamB: "EVOS",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w4m5",
    teamA: "GEEK",
    teamB: "AE",
    scoreA: 1,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w4m6",
    teamA: "ONIC",
    teamB: "TLID",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w4m7",
    teamA: "BTR",
    teamB: "RRQ",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w4m8",
    teamA: "DEWA",
    teamB: "GEEK",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  // --- WEEK 5 ---
  {
    id: "w5m1",
    teamA: "GEEK",
    teamB: "NAVI",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w5m2",
    teamA: "EVOS",
    teamB: "ONIC",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w5m3",
    teamA: "DEWA",
    teamB: "RRQ",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w5m4",
    teamA: "AE",
    teamB: "TLID",
    scoreA: 1,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w5m5",
    teamA: "EVOS",
    teamB: "BTR",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w5m6",
    teamA: "AE",
    teamB: "NAVI",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w5m7",
    teamA: "GEEK",
    teamB: "ONIC",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w5m8",
    teamA: "DEWA",
    teamB: "TLID",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  // --- WEEK 6 ---
  {
    id: "w6m1",
    teamA: "NAVI",
    teamB: "DEWA",
    scoreA: 1,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w6m2",
    teamA: "AE",
    teamB: "GEEK",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w6m3",
    teamA: "EVOS",
    teamB: "AE",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w6m4",
    teamA: "TLID",
    teamB: "ONIC",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w6m5",
    teamA: "RRQ",
    teamB: "BTR",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w6m6",
    teamA: "NAVI",
    teamB: "TLID",
    scoreA: 1,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w6m7",
    teamA: "ONIC",
    teamB: "RRQ",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w6m8",
    teamA: "GEEK",
    teamB: "EVOS",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  // --- WEEK 7 ---
  {
    id: "w7m1",
    teamA: "GEEK",
    teamB: "DEWA",
    scoreA: 1,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w7m2",
    teamA: "BTR",
    teamB: "TLID",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w7m3",
    teamA: "DEWA",
    teamB: "AE",
    scoreA: 1,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w7m4",
    teamA: "EVOS",
    teamB: "RRQ",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w7m5",
    teamA: "ONIC",
    teamB: "NAVI",
    scoreA: 2,
    scoreB: 0,
    isPlayed: true,
  },
  {
    id: "w7m6",
    teamA: "RRQ",
    teamB: "GEEK",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
  {
    id: "w7m7",
    teamA: "NAVI",
    teamB: "BTR",
    scoreA: 2,
    scoreB: 1,
    isPlayed: true,
  },
  {
    id: "w7m8",
    teamA: "TLID",
    teamB: "EVOS",
    scoreA: 0,
    scoreB: 2,
    isPlayed: true,
  },
]
const imgPre =
  "https://mpl.isan.eu.org/cdn-cgi/image/f=webp/https://res.cloudinary.com/isans/image/upload/q_auto:eco,h_60/teams/"

export interface Team {
  id: string
  name: string
  logo: string
  logoDark?: string
}

export const TEAMS: Team[] = [
  {
    id: "TLID",
    name: "Team Liquid ID",
    logo: `${imgPre}liquid_lightmode`,
    logoDark: `${imgPre}liquid_darkmode`,
  },
  {
    id: "ONIC",
    name: "ONIC Esports",
    logo: `${imgPre}onic_lightmode`,
    logoDark: `${imgPre}onic`,
  },
  {
    id: "DEWA",
    name: "Dewa United Esports",
    logo: "https://mpl.isan.eu.org/cdn-cgi/image/f=webp/https://res.cloudinary.com/isans/image/upload/q_auto:eco,h_60,w_82,c_pad/teams/dewa",
    logoDark:
      "https://mpl.isan.eu.org/cdn-cgi/image/f=webp/https://res.cloudinary.com/isans/image/upload/q_auto:eco,h_60,w_84,c_pad/teams/dewa_darkmode",
  },
  { id: "AE", name: "Alter Ego Esports", logo: `${imgPre}ae` },
  {
    id: "BTR",
    name: "Bigetron by Vitality",
    logo: `${imgPre}btrvit`,
    logoDark: `${imgPre}btrvit_darkmode`,
  },
  { id: "EVOS", name: "EVOS Esports", logo: `${imgPre}evos` },
  {
    id: "NAVI",
    name: "Natus Vincere",
    logo: `${imgPre}navi_lightmode`,
    logoDark: `${imgPre}navi_darkmode`,
  },
  { id: "GEEK", name: "Geek Fam ID", logo: `${imgPre}geek` },
  { id: "RRQ", name: "RRQ Hoshi", logo: `${imgPre}rrq` },
]
