name: Sync MPL Schedules & Scores

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9,11,13,15 * * 0,5,6'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run Sync Script
        run: npm run sync -- --push
